# Simulation settings
WIDTH, HEIGHT = 1100, 650
NUM_FISH = 50
MUTATION_RATE = 0.15
DAY_LENGTH = 360
DAYS_IN_SEASON = 6
SEASON_LENGTH = DAY_LENGTH * DAYS_IN_SEASON
LINE_LEVEL = HEIGHT - 60

VISION_REDUCTION_IN_ALGAE = 0.7
CURRENT_MOVEMENT_FACTOR = 1.15
IDLE_MOVEMENT_FACTOR = 0.2

PROFILING = False

# Fish
PREY_PREGNANCY_DUR = (DAY_LENGTH * 5, DAY_LENGTH * 8)
PREY_AFTER_BIRTH_DUR = (DAY_LENGTH * 2, DAY_LENGTH * 4)
PREDATOR_PREGNANCY_DUR = (DAY_LENGTH * 7, DAY_LENGTH * 9)
PREDATOR_AFTER_BIRTH_DUR = (DAY_LENGTH * 3, DAY_LENGTH * 5)

MAX_ENERGY = 100
SIZE_EFECT = 0.6
DEGISTION_EFECT = 0.5
REPRODUCTION_EFECT = 0.2
METABOLISM_EFECT = 0.9

OVERLAP_THRESHOLD = 0.1
APT = 0.002 # Age per tick
EAT_SIZE = 2.5

# Algae
MAX_ALGAE = 150 
INITIAL_ALGAE = 100 

ALGAE_GROW = (DAY_LENGTH, DAY_LENGTH * 1.5)
DEAD_ALGAE_LIFETIME = (DAY_LENGTH * 4, DAY_LENGTH * 7)

ALGAE_RAD = 4

# Crustaceans
INITIAL_CRUSTACEANS = 10 
CRUSTACEAN_LIFETIME = (DAY_LENGTH * 3, DAY_LENGTH * 5)

# Plankton
INITIAL_PLANKTON = 20 
PLANKTON_LIFETIME = (DAY_LENGTH * 2, DAY_LENGTH * 4)

# Temperature
MIN_TEMP = 10  
MAX_TEMP = 25  
OPTIMAL_TEMP = 20 

# Oxygen
MAX_OXYGEN = 10  
MIN_OXYGEN = 2   
OXYGEN_BOOST_RADIUS = 50  
OXYGEN_BOOST = 3  
CRITICAL_OXYGEN = 3